export function copyResults(summaryObj) {
  const lines = [];
  lines.push('📊 CalcHub — Calculator Results');
  lines.push('──────────────────────────────');
  for (const [key, value] of Object.entries(summaryObj)) {
    lines.push(`${key}: ${value}`);
  }
  lines.push('──────────────────────────────');
  lines.push('Generated by CalcHub');

  const text = lines.join('\n');

  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(text).catch(() => fallbackCopy(text));
  } else {
    fallbackCopy(text);
  }

  showToast('Copied to clipboard');
}

function fallbackCopy(text) {
  const ta = document.createElement('textarea');
  ta.value = text;
  ta.style.position = 'fixed';
  ta.style.opacity = '0';
  document.body.appendChild(ta);
  ta.select();
  try {
    document.execCommand('copy');
  } catch (e) {
    console.warn('Copy failed');
  }
  document.body.removeChild(ta);
}

let toastTimer = null;

export function showToast(message) {
  let toast = document.getElementById('toast');
  if (!toast) {
    toast = document.createElement('div');
    toast.id = 'toast';
    toast.className = 'toast';
    document.body.appendChild(toast);
  }

  if (toastTimer) {
    clearTimeout(toastTimer);
    toast.classList.remove('show');
  }

  requestAnimationFrame(() => {
    toast.textContent = message;
    toast.classList.add('show');
  });

  toastTimer = setTimeout(() => {
    toast.classList.remove('show');
  }, 2200);
}
