"use client";

import { Button } from "@/components/ui/button";
import { showToast } from "@/components/shared/Toast";
import { CalcIcon } from "@/components/shared/CalcIcon";

interface ResetCopyBarProps {
  onReset: () => void;
  summaryObj?: Record<string, string>;
}

export function ResetCopyBar({ onReset, summaryObj }: ResetCopyBarProps) {
  const handleCopy = async () => {
    if (!summaryObj) return;
    const lines = Object.entries(summaryObj).map(([k, v]) => `${k}: ${v}`);
    const text = ["FinCalc Pro", "────────────────", ...lines, "────────────────", "Generated by FinCalc Pro"].join("\n");
    try {
      await navigator.clipboard.writeText(text);
      showToast("Copied to clipboard");
    } catch {
      showToast("Could not copy");
    }
  };

  return (
    <div className="flex gap-2 flex-wrap">
      <Button variant="outline" size="default" className="min-h-11" onClick={onReset}>↺ Reset</Button>
      {summaryObj && (
        <Button variant="default" size="default" className="min-h-11" onClick={handleCopy}><CalcIcon name="📋" className="w-4 h-4 mr-1.5" /> Copy Result</Button>
      )}
    </div>
  );
}
